cloud:
  aws:
    credentials:
      access-key: ACCESS-KEY
      secret-key: SECRET-KEY
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: springboot-s3-demo1


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
